services:  
  yugabytedb-1:
    image: yugabytedb/yugabyte:latest
    container_name: yugabytedb-1
    ports:
      - "5433:5433"  # YSQL
      - "9042:9042"  # YCQL
      - "7001:7000"  # Master UI
      # - "9000:9000"  # TServer UI
      - "15433:15433"  # UI
    command: ["bin/yugabyted", "start", "--daemon=false"]
    restart: unless-stopped
    networks:
      - yugabyte-network
  yugabytedb-2:
    image: yugabytedb/yugabyte:latest
    container_name: yugabytedb-2
    ports:
      - "5434:5433"  # YSQL
      - "9043:9042"  # YCQL
      - "7002:7000"  # Master UI
      # - "9000:9000"  # TServer UI
      # - "15433:15433"  # UI
    command: ["bin/yugabyted", "start", "--daemon=false"]
    restart: unless-stopped
    networks:
    - yugabyte-network
  yugabytedb-3:
    image: yugabytedb/yugabyte:latest
    container_name: yugabytedb-3
    ports:
      - "5435:5433"  # YSQL
      - "9044:9042"  # YCQL
      - "7003:7000"  # Master UI
      # - "9000:9000"  # TServer UI
      # - "15433:15433"  # UI
    command: ["bin/yugabyted", "start", "--daemon=false"]
    restart: unless-stopped
    networks:
    - yugabyte-network
  benchbase: 
    image: benchbase.azurecr.io/benchbase
    container_name: benchbase
    user: root
    volumes:
      - ./config:/benchbase/config
      - ./results:/benchbase/results
    environment:
      - BENCHBASE_PROFILE=postgres
    depends_on:
      - yugabytedb-1
      - yugabytedb-2
      - yugabytedb-3
    command: 
      - -c /benchbase/config/yugabyte_seats_config.xml
      - -b seats
      - --create=true --load=true --execute=true
    networks:
      - yugabyte-network
networks:
  yugabyte-network:
    driver: bridge